<a href="https://colab.research.google.com/github/Elwing-Chou/tibame20260427/blob/main/tibame20260606.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


```
上次的複習(爬蟲整個流程)

1. 找到網址: a. 原始碼有  b. 原始碼沒有(F12找隱藏)
2. 解析看格式: a. JSON格式  b. HTML格式

分支1. JSON格式
1. json.loads: 字典/list解析

分支2. HTML格式
2. BeautifulSoup: 找你需要的區塊(html名字+class做篩選)

排版屬性: 在區塊上加上這些屬性來輔助排版
a. class: class="分類1 分類2"(熟悉)
b. id: id="xxx"(補充)
html.find(名字, {"id":"xxxx"})

3. 儲存+分析(pandas)


```

In [28]:
import urllib.request as req
import bs4 as bs

def get_page(page_num):
    url = f"https://tabelog.com/tw/tokyo/rstLst/sweets/{page_num}/?SrtT=rt"
    print(url)
    resp = req.urlopen(url)
    content = resp.read()
    html = bs.BeautifulSoup(content)
    rs = html.find_all("div", {"class":"list-rst__body"})

    # 最後回傳的一頁的餐廳清單
    result = []
    for r in rs:
        name = r.find("a", {"class":"list-rst__rst-name-target"})
        area_genre = r.find("div", {"class":"list-rst__area-genre"})
        rating = r.find("span", {"class":"c-rating__val"})
        prices = r.find_all("span", {"class":"c-rating-v3__val"})
        dinner_price = prices[0]
        lunch_price = prices[1]
        holiday = r.find("span", {"class":"list-rst__holiday-text"})
        imgs = r.find_all("img", {"class":"js-thumbnail-img"})

        name_text = name.get_text().strip()
        name_href = name["href"]
        area_genre_text = area_genre.get_text().strip()
        rating_text = rating.get_text().strip()
        dinner_price_text = dinner_price.get_text().strip()
        lunch_price_text = lunch_price.get_text().strip()
        holiday_text = holiday.get_text().strip()

        imgs_src = []
        for img in imgs:
            imgs_src.append(img["data-lazy"])

        # 一筆資料是一個字點
        data = {
            "rating":rating_text,
            "name":name_text,
            "link":name_href,
            "area_genre":area_genre_text,
            "price_dinner":dinner_price_text,
            "price_lunch":lunch_price_text,
            "holiday":holiday_text,
            "imgs":imgs_src,
        }
        result.append(data)

    return result

get_page(2)

https://tabelog.com/tw/tokyo/rstLst/sweets/2/?SrtT=rt

[{'rating': '3.85',
  'name': 'patisserie K.ViNCENT',
  'link': 'https://tabelog.com/tw/tokyo/A1309/A130905/13035194/',
  'area_genre': '飯田橋車站 408m / 蛋糕, 巧克力, 西式甜點',
  'price_dinner': 'JPY 10,000 - JPY 14,999',
  'price_lunch': '-',
  'holiday': '-',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/179334/320x320_square_5f70f42e1d93c672b31be6ae32a35eaa.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/179334/320x320_square_4e4d44b4f111d6a1fb7b4dc942be4bd1.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/4291/320x320_square_4291051.jpg']},
 {'rating': '3.85',
  'name': "L'AUTOMNE 中野店",
  'link': 'https://tabelog.com/tw/tokyo/A1321/A132101/13118933/',
  'area_genre': '新江古田車站 39m / 蛋糕, 咖啡店, 麵包',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期一, 星期二',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/151045/320x320_square_151045029.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/151045/320x320_square_151045100.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/151045/320x320_square_151045067.jpg']},
 {'rating': '3.84',
  'name': 'VIRON 丸之內店',
  'link': 'https://tabelog.com/tw/tokyo/A1302/A130201/13043904/',
  'area_genre': '東京車站 320m / 麵包, 蛋糕, 咖啡店',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'holiday': '-',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/228083/320x320_square_2894633ce61ee3571afdc87450647a45.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/228083/320x320_square_82e14a0eeb245f4564e8f8c2466f33d9.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/2113/320x320_square_2113939.jpg']},
 {'rating': '3.84',
  'name': 'GAZTA',
  'link': 'https://tabelog.com/tw/tokyo/A1316/A131602/13223261/',
  'area_genre': '白金高輪車站 271m / 蛋糕',
  'price_dinner': '-',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期一',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/144973/320x320_square_144973453.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/144973/320x320_square_144973443.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/173625/320x320_square_20af30023c17d3a0caf42abd1c2edf2b.jpg']},
 {'rating': '3.84',
  'name': 'Au Bon Vieux Temps 尾山台店',
  'link': 'https://tabelog.com/tw/tokyo/A1317/A131715/13181654/',
  'area_genre': '尾山台車站 368m / 蛋糕, 小菜, 咖啡店',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期二, 星期三',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/239594/320x320_square_e9741d3a6e416ba91e6330caf52ba023.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/239593/320x320_square_d5e567fbe94191e6009f0cc9cfecb4fd.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/181175/320x320_square_dc65cf23887d21edbc8da566a3ac1461.jpg']},
 {'rating': '3.84',
  'name': 'Patisserie Yu Sasage',
  'link': 'https://tabelog.com/tw/tokyo/A1318/A131809/13155662/',
  'area_genre': '千歲烏山車站 273m / 蛋糕, 麵包',
  'price_dinner': '-',
  'price_lunch': '- JPY 999',
  'holiday': '星期二, 星期三',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/235153/320x320_square_7cbf6d48bc025ddfa294fe0a3d1df480.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/232910/320x320_square_d6b9174f042edf8f17c2c7066c1ad2cc.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/19690/320x320_square_19690369.jpg']},
 {'rating': '3.84',
  'name': 'Minimal 富ヶ谷本店',
  'link': 'https://tabelog.com/tw/tokyo/A1303/A130301/13175834/',
  'area_genre': '代代木八幡車站 372m / 巧克力, 蛋糕, 咖啡店',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'holiday': '-',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/165266/320x320_square_6b23ba76ede15a32906e2724a06e7fdf.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/165879/320x320_square_5332637fcaf31d8155d6ed4120c9ea16.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/352086/320x320_square_803fe95e2e82beee97faee7fbbcd066b.jpg']},
 {'rating': '3.84',
  'name': 'patisserie Plaisir',
  'link': 'https://tabelog.com/tw/tokyo/A1317/A131706/13045491/',
  'area_genre': '西太子堂車站 672m / 蛋糕, 咖啡店',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期一, 星期二',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/289141/320x320_square_0889a397906d5383e4263f8979e6f4f1.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/289141/320x320_square_3f91197f5a04e57eef4c2c062d287fc9.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/156565/320x320_square_156565356.jpg']},
 {'rating': '3.83',
  'name': 'VIRON 澀谷店',
  'link': 'https://tabelog.com/tw/tokyo/A1303/A130301/13004626/',
  'area_genre': '澀谷車站 465m / 麵包, 三明治, 蛋糕',
  'price_dinner': '- JPY 999',
  'price_lunch': '- JPY 999',
  'holiday': '-',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/294087/320x320_square_3fc259e18e9cd0fe03e7cc37a22e4f4b.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/294087/320x320_square_3fcbea15a22e6ea28b1fe7d1a9443ed7.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/243213/320x320_square_8360478ff9aaa7478f7c9006cbf7159a.jpg']},
 {'rating': '3.83',
  'name': 'Usagiya',
  'link': 'https://tabelog.com/tw/tokyo/A1311/A131101/13003599/',
  'area_genre': '湯島車站 195m / 日式點心, 銅鑼燒',
  'price_dinner': '- JPY 999',
  'price_lunch': '- JPY 999',
  'holiday': '星期三',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/250231/320x320_square_8a11baa42fa69b956538d8e1d3680758.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/250231/320x320_square_30f0e0e9f7b494d711254ba1f582cdec.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/234861/320x320_square_525764dbee434dff36562f28beef0375.jpg']},
 {'rating': '3.83',
  'name': 'Curry Spice Gelateria KALPASI',
  'link': 'https://tabelog.com/tw/tokyo/A1318/A131802/13247887/',
  'area_genre': '下北澤車站 105m / 咖喱, 意式冰淇淋/冰淇淋, 亞洲料理, 民族料理',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期四',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/145610/320x320_square_145610447.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/145610/320x320_square_145610451.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/145610/320x320_square_145610452.jpg']},
 {'rating': '3.83',
  'name': '法國菓子 甜點師 巧克力師 Inamurashōzō',
  'link': 'https://tabelog.com/tw/tokyo/A1311/A131105/13047298/',
  'area_genre': '日暮里車站 139m / 蛋糕, 巧克力',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期一, 星期二',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/245257/320x320_square_7e04d645a02cd6f0ce33d9154873d54d.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/160744/320x320_square_160744220.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/11677/320x320_square_11677542.jpg']},
 {'rating': '3.83',
  'name': 'PATISSERIE ASAKO IWAYANAGI',
  'link': 'https://tabelog.com/tw/tokyo/A1317/A131715/13189509/',
  'area_genre': '等等力車站 232m / 蛋糕, 咖啡店',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'price_lunch': '-',
  'holiday': '星期一, 星期二',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/319400/320x320_square_39891e507587bd359e6f2c45ec165b6c.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/319400/320x320_square_a9823aba41ea046b150564aa96befe52.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/200069/320x320_square_98502c16e696b140cb978d2980950be6.jpg']},
 {'rating': '3.83',
  'name': 'Creperie Tirol',
  'link': 'https://tabelog.com/tw/tokyo/A1318/A131814/13205650/',
  'area_genre': '祖師谷大藏車站 271m / 可麗餅/法式薄餅',
  'price_dinner': '-',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期一, 星期四, 星期六',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/363306/320x320_square_90476d84cfa1eeb433d752f2f6684152.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/363306/320x320_square_17577e7e3848332d8c3fe3595290ea01.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/239308/320x320_square_5bb398e414480cf8b48ebd748d523a90.jpg']},
 {'rating': '3.83',
  'name': 'Chirimulo',
  'link': 'https://tabelog.com/tw/tokyo/A1303/A130301/13164533/',
  'area_genre': '代官山車站 614m / 蛋糕, 甜食',
  'price_dinner': '- JPY 999',
  'price_lunch': '-',
  'holiday': '星期一, 星期二, 星期三, 星期日',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/274301/320x320_square_3365ee87cce1fd916ed4938f9c19bcbc.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/274301/320x320_square_a29310fef3d306918758d4b81332e1f1.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/27665/320x320_square_2ddc396f48f0eb76578dd169e8d8dd3f.jpg']},
 {'rating': '3.83',
  'name': 'LESS by Gabriele Riva & Kanako Sakakura',
  'link': 'https://tabelog.com/tw/tokyo/A1303/A130302/13274859/',
  'area_genre': '惠比壽車站 521m / 蛋糕, 巧克力',
  'price_dinner': '-',
  'price_lunch': 'JPY 2,000 - JPY 2,999',
  'holiday': '星期三',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/363024/320x320_square_5ecab23c51742fc245e9bf205f7882ab.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/363024/320x320_square_66f8202eb37a6ab324c66ad203ccf0d7.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/363024/320x320_square_e99cfb491e167adc0e846f515f7a7890.jpg']},
 {'rating': '3.83',
  'name': 'Blondir',
  'link': 'https://tabelog.com/tw/tokyo/A1321/A132103/13184127/',
  'area_genre': '石神井公園車站 837m / 蛋糕, 麵包',
  'price_dinner': 'JPY 2,000 - JPY 2,999',
  'price_lunch': 'JPY 2,000 - JPY 2,999',
  'holiday': '星期一, 星期日',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/104373/320x320_square_104373842.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/104373/320x320_square_104373833.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/104373/320x320_square_104373804.jpg']},
 {'rating': '3.82',
  'name': "Nata de Cristiano's",
  'link': 'https://tabelog.com/tw/tokyo/A1318/A131810/13153384/',
  'area_genre': '代代木公園車站 185m / 甜食, 麵包, 蛋糕',
  'price_dinner': '- JPY 999',
  'price_lunch': '- JPY 999',
  'holiday': '-',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/267100/320x320_square_c21338cc01d30cfd70c7fa27c6e3c939.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/267100/320x320_square_b49c5ea34bea0ff4018d835801b2c092.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/205432/320x320_square_db7c9e5b812a66704dd01ff41cd4bf58.jpg']},
 {'rating': '3.82',
  'name': '和光Tea Salon',
  'link': 'https://tabelog.com/tw/tokyo/A1301/A130101/13009081/',
  'area_genre': '銀座車站 53m / 咖啡店, 蛋糕',
  'price_dinner': 'JPY 3,000 - JPY 3,999',
  'price_lunch': 'JPY 3,000 - JPY 3,999',
  'holiday': '-',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/231958/320x320_square_f36f84382e415950226094e985045fc8.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/230501/320x320_square_31748572ccfc8638d41c7258ee8e0900.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/224184/320x320_square_28d98d7a029d81dd0589c962f143ac0a.jpg']},
 {'rating': '3.82',
  'name': 'La Maison du Chocolat 丸之內店',
  'link': 'https://tabelog.com/tw/tokyo/A1301/A130102/13000036/',
  'area_genre': '有樂町車站 186m / 巧克力, 蛋糕, 咖啡店',
  'price_dinner': '-',
  'price_lunch': 'JPY 3,000 - JPY 3,999',
  'holiday': '-',
  'imgs': ['https://tblg.k-img.com/restaurant/images/Rvw/347398/320x320_square_bea1d03d753c327c1f5b8ad36d2383e3.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/347398/320x320_square_2b7c05b12907d107636a537bac20d8ef.jpg',
   'https://tblg.k-img.com/restaurant/images/Rvw/347398/320x320_square_d4b4443f2a181d24ca4b585ff2eec7d9.jpg']}]

In [53]:
# [{}餐廳, {}餐廳] -> dataframe
import pandas as pd

total = []
for i in range(5):
    page = i + 1
    partial = get_page(page)
    total = total + partial

df = pd.DataFrame(total)
df

https://tabelog.com/tw/tokyo/rstLst/sweets/1/?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/sweets/2/?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/sweets/3/?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/sweets/4/?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/sweets/5/?SrtT=rt

,rating,name,link,area_genre,price_dinner,price_lunch,holiday,imgs
0,4.24,Bon.nu,https://tabelog.com/tw/tokyo/A1304/A130401/131...,"參宮橋車站 356m / 法式料理, 牛排, 蛋糕","JPY 50,000 - JPY 59,999","JPY 50,000 - JPY 59,999",-,[https://tblg.k-img.com/restaurant/images/Rvw/...
1,4.20,Okashiya Ucchi,https://tabelog.com/tw/tokyo/A1309/A130901/132...,"北參道車站 250m / 蛋糕, 西式甜點",-,"JPY 5,000 - JPY 5,999",星期一,[https://tblg.k-img.com/restaurant/images/Rvw/...
2,4.16,蒼菓,https://tabelog.com/tw/tokyo/A1307/A130703/132...,廣尾車站 702m / 甜食,"JPY 15,000 - JPY 19,999","JPY 15,000 - JPY 19,999","星期一, 星期二, 星期日",[https://tblg.k-img.com/restaurant/images/Rvw/...
3,4.15,Yama,https://tabelog.com/tw/tokyo/A1316/A131602/132...,白金台車站 725m / 甜食,"JPY 20,000 - JPY 29,999","JPY 30,000 - JPY 39,999","星期二, 星期三",[https://tblg.k-img.com/restaurant/images/Rvw/...
4,4.05,ESPRIT C. KEI GINZA,https://tabelog.com/tw/tokyo/A1301/A130101/132...,"銀座車站 330m / 法式料理, 甜食","JPY 30,000 - JPY 39,999",-,"星期一, 星期日",[https://tblg.k-img.com/restaurant/images/Rvw/...
...,...,...,...,...,...,...,...,...
95,3.77,秘密堂,https://tabelog.com/tw/tokyo/A1311/A131106/131...,"日暮里車站 376m / 刨冰, 日式甜點店","JPY 2,000 - JPY 2,999","JPY 1,000 - JPY 1,999","星期一, 星期二",[https://tblg.k-img.com/restaurant/images/Rvw/...
96,3.77,Fruit Parlour Goto,https://tabelog.com/tw/tokyo/A1311/A131102/130...,"淺草車站 224m / 水果聖代, 咖啡店, 刨冰","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999","星期三, 星期四",[https://tblg.k-img.com/restaurant/images/Rvw/...
97,3.77,MAISON LANDEMAINE 麻布台,https://tabelog.com/tw/tokyo/A1307/A130701/131...,"六本木一丁目車站 429m / 麵包, 西式甜點, 咖啡店","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-,[https://tblg.k-img.com/restaurant/images/Rvw/...
98,3.77,FRENCH POUND HOUSE 大和鄉本店,https://tabelog.com/tw/tokyo/A1323/A132301/130...,"巢鴨車站 228m / 蛋糕, 咖啡店","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-,[https://tblg.k-img.com/restaurant/images/Rvw/...
99,3.77,和kitchen Kanna,https://tabelog.com/tw/tokyo/A1317/A131706/131...,"三軒茶屋車站 750m / 刨冰, 創作料理",-,"JPY 1,000 - JPY 1,999",星期三,[https://tblg.k-img.com/restaurant/images/Rvw/...

In [19]:
# demo: 如何下載一筆圖片
import urllib.request as req

url = "https://japan.videoland.com.tw/images/contents/20250821144057983.png"
h = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0"
}
r = req.Request(url, headers=h)

resp = req.urlopen(r)
content = resp.read()

# 開一個空白檔案, 把content寫進去
# 純文字: f = open(檔名, "w", encoding="utf-8") "r" or "w"
# 其它(jpg, jpeg, png, pdf, docx): f = open("檔名", "rb") "rb" or "wb"
f = open("a.png", "wb")
f.write(content)
f.close()

In [ ]:
# DataFrame: pandas表格型態(二維)
# Series: pandas list型態(一維)
import os
import time
import urllib.request as req

dn = "tabelog2"
if not os.path.exists(dn):
    os.makedirs(dn)
for d in df["imgs"]:
    for img in d:
        print(img)
        # 每一個圖片網址
        fp = f"{dn}/{time.time()}.png"
        h = {
            "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0"
        }
        r = req.Request(img, headers=h)
        resp = req.urlopen(r)
        content = resp.read()
        # 開一個新檔案, 把你從網址讀出來的內容寫入
        f = open(fp, "wb")
        f.write(content)
        f.close()


```
pandas 第二個你要會的

apply: 轉換

Python: Everything is an object
這句話只跟你說了一件事: 任何東西都有形態, 每個型態都有他的操作

List型態: [] 操作: 拿key/append/for...in/*
!!! 函式也有形態

函式: 把很多句程式組合在一起變成一個步驟
以前: randint(0, 2)
現在: 其實是分開的

步驟型態: randint  操作: (0, 2)
刷牙步驟        操作: ()

```

In [38]:
def add(n1, n2):
    n = n1 + n2
    n = round(n)
    return n

b = add
b(3.2, 5.6)

9

In [ ]:
# demo: Series.apply(錦囊)

demo = pd.DataFrame([
    [1, 2],
    [3, 4],
    [5, 6]
], columns=["a", "b"])
# 1. 使用已經有的錦囊
demo["a"].apply(float)
# 2. 自己定義功能
def func(n):
    import random
    n = n + random.uniform(-1, 1)
    return n
demo["a"].apply(func)

In [59]:
def func(s):
    # 如果你想把他變成多格, 回傳Series
    d = {
        "星期一":"y",
        "星期二":"y",
        "星期三":"y",
        "星期四":"y",
        "星期五":"y",
        "星期六":"y",
        "星期日":"y",
    }
    for k in d:
        if k in s:
            d[k] = "n"
    return pd.Series(d)

new = df["holiday"].apply(func)
# df[['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日']] = new
# df
# 結合過濾
fil1 = new["星期六"] == "n"
fil2 = new["星期日"] == "n"
fil = fil1 & fil2
df[fil]

,rating,name,link,area_genre,price_dinner,price_lunch,holiday,imgs
83,3.78,清壽軒,https://tabelog.com/tw/tokyo/A1302/A130204/132...,"小傳馬町車站 319m / 日式點心, 銅鑼燒",-,- JPY 999,"星期六, 星期日, 節假日",[https://tblg.k-img.com/restaurant/images/Rvw/...
91,3.78,STYLE'S CAKES & CO.,https://tabelog.com/tw/tokyo/A1310/A131003/131...,神保町車站 232m / 蛋糕,"JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999","星期三, 星期六, 星期日, 節假日",[https://tblg.k-img.com/restaurant/images/Rvw/...

In [48]:
d = {
    "星期一":"y",
    "星期二":"y",
    "星期三":"y",
    "星期四":"y",
    "星期五":"y",
    "星期六":"y",
    "星期日":"y",
}
for k in d:
    print(k)

星期一
星期二
星期三
星期四
星期五
星期六
星期日